### ISSUE TITLE
Fix sed on MacOS

### ISSUE THREAD

**Issue by OmarElawady** [OmarElawady/crpgp#2]
sed apparently has some differences between OSX and linux doesn't. The Makefile should be adapted to work with both.

**Comment by sameh-farouk** [comment]
macOS uses the BSD version of sed, which differs in many respects from the GNU sed version that comes with Linux distros.
If you need to support BOTH platforms, there are two solutions:
1- restrict your sed scripts to what BSD sed supports, they will generally work in GNU sed too - with the notable exception of using platform-specific extended regex features with `-E`.
checking current sed script, I can spot these Incompatible features:
- Use of the `-i` option without an argument (in-place updating without backup) is incompatible. in BSD sed it MUST use `-i ''` which won't work on GNU sed. This can be easily adapted to work on both platforms, e.g, using a backup)
- OS X's sed / BSD sed doesn't support  `-z` (`--null-data`).
- The BSD implementation of sed additionally does not support \b as a word boundary pattern. it uses `[[:<:]]` and `[[:>:]]` instead.
- `\n` will be treated literally within a replacement string.

it may be possible but it is a headache to find a syntax that would run flawlessly on both platforms, in the meantime, there is an easier solution.

2- the other option is to use homebrew to install GNU version of sed for MacOS
```sh
brew install gnu-sed
export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"
```
then it would work just fine as it works on Linux, tested. running `make runv` would succeed in macOS 10.15 after installing gnu-sed. note that the commands above add gnu-sed to PATH only temporally to make it the default sed command so you can run the make scripts. closing the shell have the effect of restoring BSD sed as the default one.
 
<img width="1280" alt="Screen Shot 2022-02-23 at 7 18 23 PM" src="https://user-images.githubusercontent.com/42457449/155381295-dfef17bf-c251-4e4d-b571-26297e5c1bc8.png">
